### ISSUE TITLE
A couple of missed distillery release paths

### ISSUE THREAD

**Issue by grossvogel** [revelrylabs/revelry_phoenix_app_template#257]
It looks like the [inter-stage `COPY`](https://github.com/revelrylabs/revelry_phoenix_app_template/blob/b970b30d8f1e08a8b11427ac9e344fac0b7f21df/Dockerfile#L54) in the `Dockerfile` and [the `exec` command](https://github.com/revelrylabs/revelry_phoenix_app_template/blob/01878fd75f7613d6e29892bc83d4e2a64276eb92/bin/remote_console#L9) in `bin/remote_console` are still using the path to the distillery binary rather than the new one in `/bin`

https://github.com/revelrylabs/revelry_phoenix_app_template/search?q=%22_build%2Fprod%2Frel%22&unscoped_q=%22_build%2Fprod%2Frel%22

**Comment by bryanjos** [comment]
The one in the dockerfile is fine (distillery and elixir releases go the same place). We will have to update the remote_console bin though. I made a PR for it

**Comment by grossvogel** [comment]
Ah, yeah, I see what's happening in the Dockerfile now, thanks
