### ISSUE TITLE
User - Session Storage - Persist correctly in multi-node deployments

### ISSUE THREAD

**Issue by grossvogel** [revelrylabs/revelry_phoenix_app_template#537]
## Background
I haven't researched this thoroughly yet, but there's reason to believe our Pow configuration is using ETS as its session storage mechanism, and that this will cause problems when the app is deployed across multiple nodes. A user who initiates a session while connected to node A will not be recognized as logged-in by node B, and vice versa.

## Scenario: Insert Scenario Here
Given I am an Engineer creating a new app from the template
- [ ] When I use the default session implementation
- [ ] And then I deploy my app across multiple nodes
- [ ] Then a common session store is available to all nodes rather than each node having its own

Given I am a User using a new app based on the template and deployed on multiple nodes
- [ ] When I sign in
- [ ] Then I stay signed-in until my session expires no matter which node services my requests

NOTE: It may be decided that there's no one-size-fits-all best default configuration. In that case feel free to deviate from the "default" language above and document multiple "recommended" configurations. Somebody starting a fresh app and deploying it from multiple nodes shouldn't be on their own to figure this out.

**Comment by grossvogel** [comment]
NOTE: One thing that's been used is `pow_postgres_store`, but that may not be ideal because it creates a lot of database activity.

**Comment by brianberlin** [comment]
The other issue is that the ETS store will be wiped when releasing new code.

**Comment by danschultzer** [comment]
👋 I recommend reading up on https://hexdocs.pm/pow/1.0.18/production_checklist.html#required-use-a-persistent-cache-store and https://hexdocs.pm/pow/1.0.18/Pow.Store.Backend.MnesiaCache.html#module-distribution

**Comment by Harleymckee** [comment]
Oh does this issue stand with normal pow phoenix session auth? 

I was under the impression that Pow does not use ETS at all in its normal phoenix session handling, Bob copied an implementation of token based auth (that's in pow doc) for mobile app that did, and explicitly made calls to `Pow.Store.Backend.EtsCache`.

Re mobile authentication:
I think we should plug and play with @danschultzer Oauth provider lib for out Mobile app Auth to have a complete Oauth implementation, not the approximation we looked at before. 

see this pr (will be submitting for review today) https://github.com/revelrylabs/revelry_phoenix_app_template/pull/540/ .

**Comment by Harleymckee** [comment]
That was a tangent, and not really within the scope of this issue.

In a word, I don't think there's anything wrong with existing code here.

**Comment by grossvogel** [comment]
Cool, thanks. It looks like currently we're relying on the Phoenix session, which is configured to use the cookie store and should therefore work fine across multiple nodes. Closing this one, thanks all!
