### ISSUE TITLE
DevOps - add a health check endpoint

### ISSUE THREAD

**Issue by grossvogel** [revelrylabs/revelry_phoenix_app_template#639]
Lots of deployment environments benefit from a health check endpoint that can be accessed to verify whether the app is completely up and responsive. For example, with no readiness probe defined, a k8s deployment using rolling updates will start sending traffic to a pod as soon as it's "Running" but potentially before the app is completely ready to receive requests. Having a liveness probe may also allow the cluster to more accurately detect crashed pods and restart them.

We should add an endpoint that simply returns a 200 response as long as the app is up and can be used in liveness and readiness probes.

**Comment by oohnoitz** [comment]
This should be fairly quick and easy to implement with https://github.com/whatyouhide/plug_heartbeat so we don't have to write custom code that does the same thing.
