### ISSUE TITLE
`[webpack-cli] Unknown argument: --watch-stdin` with recent Webpack upgrade

### ISSUE THREAD

**Issue by grossvogel** [revelrylabs/revelry_phoenix_app_template#811]

**Comment by oohnoitz** [comment]
I actually ran into this when upgrading myself. Just need to make the following changes to `config/dev.exs` and replace `--watch-stdin` with `--watch --watch-options-stdin`.

**Comment by grossvogel** [comment]
@oohnoitz I don't see `--watch-options-stdin` in the docs and get an error when I use it (webpack-cli v4.1)... at the same time, webpack seems to exit cleanly when I just use `--watch`, so I'm not sure anything else is needed?

**Comment by oohnoitz** [comment]
It was listed when I did `npx webpack-cli --help` and looked at https://github.com/webpack/webpack-cli/blob/master/packages/webpack-cli/README.md. though it was when i switched to webpack v5 and webpack-cli v4.1.

**Comment by grossvogel** [comment]
OK, maybe the difference is the webpack core version, since we're still on 4. Thanks!
